<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'a5a44e23ace0d7091d26d072cca21cdb' => $baseDir . '/features/wp-property-agents/loader.php',
    '51586b10f6b255677916528b236fc466' => $baseDir . '/features/wp-property-responsive-slideshow/loader.php',
    '908b1da117a8a871817a375f7853341a' => $baseDir . '/features/wp-property-supermap/loader.php',
    'f32e97dedfe851d55e4522a8b09dcb5a' => $baseDir . '/features/wp-property-terms/loader.php',
    'aa33d7d08765e2232d2271599fc1e7eb' => $baseDir . '/features/wp-rets-client/loader.php',
);
